### PR TITLE
Final submission for the challenge by JohnKat

### PR DESCRIPTION
**Pull request by Johnkat-Mj**

### CODE REVIEW

**Comment by boazpoolman** [comment]
Hey @Johnkat-Mj!

As you might've read [here](https://strapi.io/blog/announcing-the-strapi-community-competition-winners) you've taken the 1st place in the website development competition!

To collect your prize money you have to submit an expense to the Strapi Open Collective for **$500**. You can do that by clicking this link: https://opencollective.com/strapi/expenses/new.

After you've submitted the expense I'll ask you to confirm here in this chat that the expense was made by you and then we'll handle the payout!

Please if you have any questions please feel free to reach out to me in a DM on Discord. My Discord handle is **boazpoolman#3868**.

And again congratulations on your 1st place! 🥇

**Comment by boazpoolman** [comment]
Hi @Johnkat-Mj,

Can you confirm that the expense listed below was created by you?

https://opencollective.com/strapi/expenses/128277

**Comment by Johnkat-Mj** [comment]
Yes, it's me

Le mar. 14 mars 2023 à 18:55, Boaz Poolman ***@***.***> a
écrit :

**Comment by boazpoolman** [comment]
Hi @Johnkat-Mj 
Your expense is approved! The payout will happen soon.

Thanks again for participating 🎉

**Pull request merged**
